### ISSUE TITLE
Implement unnamed parameters for anonymous functions 

### ISSUE THREAD

**Issue by johnmarriott** [BSteffaniak/Nova#225]
E.g. `(_ + _)` equivalent to `(x, y) => x + y`

**Comment by BSteffaniak** [comment]
Terrible idea. Who are you?

**Comment by BSteffaniak** [comment]
Actually, since parameterless lambdas can already be specified like `array.filter({ expression })` it would be easy to implement underscores like `array.filter({ _.size < 10 })`

good idea

**Comment by BSteffaniak** [comment]
It was easier to implement this by also adding support for referencing the lambda's parameters by index. e.g. `var sumArray = array1.zip(array2, { _1 + _2 })`. In your opinion should the index start at 0 or 1? I kind of feel like counting numbers is a more natural fit for parameter indices.

`var sumArray = array1.zip(array2, { _1 + _2 })` or
`var sumArray = array1.zip(array2, { _0 + _1 })`

**Comment by johnmarriott** [comment]
I think the index should start at 1.  It matches, e.g., Haskell, ML, and Scala: http://stackoverflow.com/a/8275750/5911238
